"""add specialization field

Revision ID: f3c6747cfec9
Revises: b53cb70ea002
Create Date: 2023-09-20 16:15:07.865683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3c6747cfec9'
down_revision = 'b53cb70ea002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_data', schema=None) as batch_op:
        batch_op.drop_column('specialization')

    # ### end Alembic commands ###
